name: CICD Docker
on:
  push:
    branches:
      - master
jobs:
  continious-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest version repository
        uses: actions/checkout@v4
      
      - name: Check the code
        run: ls

      - name: Test the code
        run: go test -v ./...

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build code to Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: fakhriabdillah/training-centria-ykkbi:1.${{ github.run_number }}
